### ISSUE TITLE
Distinct case for css classes and id

### ISSUE THREAD

**Issue by benjamin-dreux** [xmlet/HtmlApiFaster#5]
Usage of css classes in html document is pretty important. Currently it's supported and it's fine.

But after I think there should be special cases for css classes and id.

I understand that at the moment both attribute are derived from xsd file which is great.

But when creating an app with html flow and htmlApiFaster,  almost every element will have a css classe and or an id.

Similar to what is the case with other template language such as pug.
I propose that we introduce an argument to every element that could receive a class or an id.
That argument is a string in the following form.

```
    .div("#my-personal-id any-other-class")
```

of course this mean that we could introduce two id, which could be checked at runtime.
Also we shall decide what happend with both the argument and the regular `attrClass` are called

**Comment by fmcarvalho** [comment]
HtmlFlow and HtmlApiFaster prioritize a type-safe approach. Given your example, the recommended usage would be:
```java
.div().attrId("my-personal-id").attrClass("any-other-class")...
```

Your proposal, however, lacks strong type safety and mixes in the query selector idiom, which seems inconsistent. I'm not seeing the advantage of your proposed approach.
